#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TxtInterfaces.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="VFTXT_IFACES")]
	public partial class TxtIfacesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public TxtIfacesDataContext() : 
				base(global::TxtInterfaces.Properties.Settings.Default.VFTXT_IFACESConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public TxtIfacesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TxtIfacesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TxtIfacesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TxtIfacesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Interface_GetParams")]
		public ISingleResult<sp_Interface_GetParamsResult> sp_Interface_GetParams([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string userid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid);
			return ((ISingleResult<sp_Interface_GetParamsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Interface_GetFcstModels")]
		public ISingleResult<sp_Interface_GetFcstModelsResult> sp_Interface_GetFcstModels()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_Interface_GetFcstModelsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Interface_UpdSeason")]
		public int sp_Interface_UpdSeason([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Add", DbType="Bit")] System.Nullable<bool> add, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fcst_model", DbType="VarChar(3)")] string fcst_model, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fcst_collection", DbType="VarChar(10)")] string fcst_collection, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fcst_collection_desc", DbType="VarChar(40)")] string fcst_collection_desc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fcst_coll_Level", DbType="Int")] System.Nullable<int> fcst_coll_Level, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fcst_coll_Father", DbType="VarChar(10)")] string fcst_coll_Father, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Priority", DbType="SmallInt")] System.Nullable<short> priority, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SMU_flag", DbType="Int")] System.Nullable<int> sMU_flag, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Coll_previous", DbType="VarChar(10)")] string coll_previous, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Coll_Previous_Same_Season", DbType="VarChar(10)")] string coll_Previous_Same_Season, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Deleted_flag", DbType="Int")] System.Nullable<int> deleted_flag)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), add, fcst_model, fcst_collection, fcst_collection_desc, fcst_coll_Level, fcst_coll_Father, priority, sMU_flag, coll_previous, coll_Previous_Same_Season, deleted_flag);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Interface_GetSeasons")]
		public ISingleResult<sp_Interface_GetSeasonsResult> sp_Interface_GetSeasons()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_Interface_GetSeasonsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Interface_GetCountries")]
		public ISingleResult<sp_Interface_GetCountriesResult> sp_Interface_GetCountries()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_Interface_GetCountriesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Interface_UpdCountry")]
		public int sp_Interface_UpdCountry([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Add", DbType="Bit")] System.Nullable<bool> add, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fcst_model", DbType="VarChar(3)")] string fcst_model, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CountryId", DbType="VarChar(50)")] string countryId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CountryDesc", DbType="VarChar(50)")] string countryDesc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Country_Level", DbType="Int")] System.Nullable<int> country_Level, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Country_FatherId", DbType="VarChar(1)")] string country_FatherId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CrossCountryId", DbType="VarChar(50)")] string crossCountryId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Currency_code", DbType="VarChar(3)")] string currency_code, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Deleted_flag", DbType="Int")] System.Nullable<int> deleted_flag)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), add, fcst_model, countryId, countryDesc, country_Level, country_FatherId, crossCountryId, currency_code, deleted_flag);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Interface_GetCustomers")]
		public ISingleResult<sp_Interface_GetCustomersResult> sp_Interface_GetCustomers()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_Interface_GetCustomersResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Interface_UpdCustomers")]
		public int sp_Interface_UpdCustomers([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Add", DbType="Bit")] System.Nullable<bool> add, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fcst_model", DbType="VarChar(3)")] string fcst_model, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fcst_customer", DbType="VarChar(8)")] string fcst_customer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fcst_customerD", DbType="VarChar(80)")] string fcst_customerD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fcst_Cust_Level", DbType="Int")] System.Nullable<int> fcst_Cust_Level, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fcst_Cust_Father", DbType="VarChar(10)")] string fcst_Cust_Father, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fcst_Excluded", DbType="Int")] System.Nullable<int> fcst_Excluded, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fcst_Cust_Type", DbType="VarChar(5)")] string fcst_Cust_Type, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Deleted_flag", DbType="Int")] System.Nullable<int> deleted_flag)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), add, fcst_model, fcst_customer, fcst_customerD, fcst_Cust_Level, fcst_Cust_Father, fcst_Excluded, fcst_Cust_Type, deleted_flag);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Interface_GetXCustomers")]
		public ISingleResult<sp_Interface_GetXCustomersResult> sp_Interface_GetXCustomers()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_Interface_GetXCustomersResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Interface_GetXCountries")]
		public ISingleResult<sp_Interface_GetXCountriesResult> sp_Interface_GetXCountries()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_Interface_GetXCountriesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Interface_UpdXCustomers")]
		public int sp_Interface_UpdXCustomers([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Add", DbType="Int")] System.Nullable<int> add, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fcst_model", DbType="VarChar(3)")] string fcst_model, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string customer_code, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string customer_door, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string crosscustomer_code, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string crosscustomer_door, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string crosscustomer_country, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Deleted_flag", DbType="Int")] System.Nullable<int> deleted_flag)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), add, fcst_model, customer_code, customer_door, crosscustomer_code, crosscustomer_door, crosscustomer_country, deleted_flag);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Interface_UpdImpSeason")]
		public int sp_Interface_UpdImpSeason([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Add", DbType="Bit")] System.Nullable<bool> add, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fcst_model", DbType="VarChar(3)")] string fcst_model, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fcst_collection", DbType="VarChar(10)")] string fcst_collection, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fcst_ImportActive", DbType="Int")] System.Nullable<int> fcst_ImportActive, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DueDateFrom", DbType="SmallDateTime")] System.Nullable<System.DateTime> dueDateFrom, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DueDateTo", DbType="SmallDateTime")] System.Nullable<System.DateTime> dueDateTo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SFA_Collection", DbType="VarChar(10)")] string sFA_Collection, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Storedatefrom", DbType="SmallDateTime")] System.Nullable<System.DateTime> storedatefrom, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Storedateto", DbType="SmallDateTime")] System.Nullable<System.DateTime> storedateto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeadlineDate", DbType="SmallDateTime")] System.Nullable<System.DateTime> deadlineDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ForecastingUntilDate", DbType="SmallDateTime")] System.Nullable<System.DateTime> forecastingUntilDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Deleted_flag", DbType="Int")] System.Nullable<int> deleted_flag)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), add, fcst_model, fcst_collection, fcst_ImportActive, dueDateFrom, dueDateTo, sFA_Collection, storedatefrom, storedateto, deadlineDate, forecastingUntilDate, deleted_flag);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Interface_GetImpSeasons")]
		public ISingleResult<sp_Interface_GetImpSeasonsResult> sp_Interface_GetImpSeasons()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_Interface_GetImpSeasonsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Interface_GetEopsSeasons")]
		public ISingleResult<sp_Interface_GetEopsSeasonsResult> sp_Interface_GetEopsSeasons()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_Interface_GetEopsSeasonsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Interface_GetProdCat")]
		public ISingleResult<sp_Interface_GetProdCatResult> sp_Interface_GetProdCat()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_Interface_GetProdCatResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Calc_EOPS")]
		public int sp_Calc_EOPS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FCST_MODEL", DbType="VarChar(3)")] string fCST_MODEL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fcst_Collection", DbType="VarChar(10)")] string fcst_Collection, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Product_Category", DbType="VarChar(20)")] string product_Category, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Replace", DbType="Int")] System.Nullable<int> replace, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DUMP", DbType="Int")] System.Nullable<int> dUMP)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fCST_MODEL, fcst_Collection, product_Category, replace, dUMP);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Interface_GetImportCustomers")]
		public ISingleResult<sp_Interface_GetImportCustomersResult> sp_Interface_GetImportCustomers()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_Interface_GetImportCustomersResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Interface_UpdImportCustomers")]
		public int sp_Interface_UpdImportCustomers(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Add", DbType="Int")] System.Nullable<int> add, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fcst_model", DbType="VarChar(3)")] string fcst_model, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fcst_Priority", DbType="Int")] System.Nullable<int> fcst_Priority, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fcst_Customer", DbType="VarChar(8)")] string fcst_Customer, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Customer_code", DbType="VarChar(20)")] string customer_code, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Delivery_addresscode", DbType="VarChar(20)")] string delivery_addresscode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Collection_From", DbType="VarChar(5)")] string collection_From, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Collection_To", DbType="VarChar(5)")] string collection_To, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Product_Category_From", DbType="VarChar(40)")] string product_Category_From, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Product_Category_To", DbType="VarChar(40)")] string product_Category_To, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Division", DbType="VarChar(20)")] string division, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalesRegion", DbType="VarChar(20)")] string salesRegion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CCSalesRegion", DbType="VarChar(20)")] string cCSalesRegion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClassIDFrom", DbType="VarChar(20)")] string classIDFrom, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClassIDto", DbType="VarChar(20)")] string classIDto, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Definition_level", DbType="Int")] System.Nullable<int> definition_level, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Comment", DbType="VarChar(255)")] string comment, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Deleted_flag", DbType="Int")] System.Nullable<int> deleted_flag)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), add, fcst_model, fcst_Priority, fcst_Customer, customer_code, delivery_addresscode, collection_From, collection_To, product_Category_From, product_Category_To, division, salesRegion, cCSalesRegion, classIDFrom, classIDto, definition_level, comment, deleted_flag);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Interface_GetCustomersDoors")]
		public ISingleResult<sp_Interface_GetCustomersDoorsResult> sp_Interface_GetCustomersDoors()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_Interface_GetCustomersDoorsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Interface_CopyCfgTxtvsSap")]
		public int sp_Interface_CopyCfgTxtvsSap([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fcst_model", DbType="VarChar(3)")] string fcst_model, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sapssnyr, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string txtcollection, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string collectionFrom)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fcst_model, sapssnyr, txtcollection, collectionFrom);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Interface_GetCfgSplitChannel")]
		public ISingleResult<sp_Interface_GetCfgSplitChannelResult> sp_Interface_GetCfgSplitChannel()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_Interface_GetCfgSplitChannelResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Interface_UpdCfgSplitChannel")]
		public int sp_Interface_UpdCfgSplitChannel([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Add", DbType="Bit")] System.Nullable<bool> add, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fcst_model", DbType="VarChar(3)")] string fcst_model, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SplitChannel", DbType="VarChar(5)")] string splitChannel, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MainChannel", DbType="VarChar(5)")] string mainChannel, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Deleted_flag", DbType="Int")] System.Nullable<int> deleted_flag)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), add, fcst_model, splitChannel, mainChannel, deleted_flag);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Interface_GetPlants")]
		public ISingleResult<sp_Interface_GetPlantsResult> sp_Interface_GetPlants()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_Interface_GetPlantsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Interface_GetSAPvsTxt")]
		public ISingleResult<sp_Interface_GetSAPvsTxtResult> sp_Interface_GetSAPvsTxt()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_Interface_GetSAPvsTxtResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Interface_GetDCs")]
		public ISingleResult<sp_Interface_GetDCsResult> sp_Interface_GetDCs()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_Interface_GetDCsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Interface_UpdPlants")]
		public int sp_Interface_UpdPlants([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Add", DbType="Bit")] System.Nullable<bool> add, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fcst_model", DbType="VarChar(3)")] string fcst_model, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fcst_Plant", DbType="VarChar(5)")] string fcst_Plant, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> priority, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fcst_DC", DbType="VarChar(10)")] string fcst_DC, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Deleted_flag", DbType="Int")] System.Nullable<int> deleted_flag)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), add, fcst_model, fcst_Plant, priority, fcst_DC, deleted_flag);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Interface_UpdSAPvsTxt")]
		public int sp_Interface_UpdSAPvsTxt(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Add", DbType="Int")] System.Nullable<int> add, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fcst_model", DbType="VarChar(3)")] string fcst_model, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string sapreqseg, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string sapplant, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sapssnyr, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string sapssn, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string txtcoll, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string txtchannel, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string txtordertype, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string txtcustomer, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> export, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string sapextregid, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> alignso, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> fcst, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> offset, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> useplant, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string fcst_dc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), add, fcst_model, sapreqseg, sapplant, sapssnyr, sapssn, txtcoll, txtchannel, txtordertype, txtcustomer, export, sapextregid, alignso, fcst, offset, useplant, fcst_dc);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Interface_GetSizeSplit")]
		public ISingleResult<sp_Interface_GetSizeSplitResult> sp_Interface_GetSizeSplit()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_Interface_GetSizeSplitResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Interface_UpdSizeSplit")]
		public int sp_Interface_UpdSizeSplit([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Add", DbType="Bit")] System.Nullable<bool> add, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fcst_model", DbType="VarChar(3)")] string fcst_model, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Collection", DbType="VarChar(10)")] string collection, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CollectionHistory", DbType="VarChar(10)")] string collectionHistory, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Deleted_flag", DbType="Int")] System.Nullable<int> deleted_flag)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), add, fcst_model, collection, collectionHistory, deleted_flag);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class sp_Interface_GetParamsResult
	{
		
		private string _acc;
		
		public sp_Interface_GetParamsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_acc", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string acc
		{
			get
			{
				return this._acc;
			}
			set
			{
				if ((this._acc != value))
				{
					this._acc = value;
				}
			}
		}
	}
	
	public partial class sp_Interface_GetFcstModelsResult
	{
		
		private string _fcst_model;
		
		public sp_Interface_GetFcstModelsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fcst_model", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string fcst_model
		{
			get
			{
				return this._fcst_model;
			}
			set
			{
				if ((this._fcst_model != value))
				{
					this._fcst_model = value;
				}
			}
		}
	}
	
	public partial class sp_Interface_GetSeasonsResult
	{
		
		private string _Fcst_model;
		
		private string _Fcst_collection;
		
		private string _Fcst_collection_desc;
		
		private int _Fcst_coll_Level;
		
		private string _Fcst_coll_Father;
		
		private System.Nullable<short> _Priority;
		
		private int _SMU_flag;
		
		private string _Coll_previous;
		
		private string _Coll_Previous_Same_Season;
		
		private System.Nullable<System.DateTime> _Log_upd_time;
		
		private string _Log_upd_user;
		
		private System.Nullable<int> _Deleted_flag;
		
		public sp_Interface_GetSeasonsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_model", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string Fcst_model
		{
			get
			{
				return this._Fcst_model;
			}
			set
			{
				if ((this._Fcst_model != value))
				{
					this._Fcst_model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_collection", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Fcst_collection
		{
			get
			{
				return this._Fcst_collection;
			}
			set
			{
				if ((this._Fcst_collection != value))
				{
					this._Fcst_collection = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_collection_desc", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Fcst_collection_desc
		{
			get
			{
				return this._Fcst_collection_desc;
			}
			set
			{
				if ((this._Fcst_collection_desc != value))
				{
					this._Fcst_collection_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_coll_Level", DbType="Int NOT NULL")]
		public int Fcst_coll_Level
		{
			get
			{
				return this._Fcst_coll_Level;
			}
			set
			{
				if ((this._Fcst_coll_Level != value))
				{
					this._Fcst_coll_Level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_coll_Father", DbType="VarChar(10)")]
		public string Fcst_coll_Father
		{
			get
			{
				return this._Fcst_coll_Father;
			}
			set
			{
				if ((this._Fcst_coll_Father != value))
				{
					this._Fcst_coll_Father = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priority", DbType="SmallInt")]
		public System.Nullable<short> Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this._Priority = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMU_flag", DbType="Int NOT NULL")]
		public int SMU_flag
		{
			get
			{
				return this._SMU_flag;
			}
			set
			{
				if ((this._SMU_flag != value))
				{
					this._SMU_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Coll_previous", DbType="VarChar(10)")]
		public string Coll_previous
		{
			get
			{
				return this._Coll_previous;
			}
			set
			{
				if ((this._Coll_previous != value))
				{
					this._Coll_previous = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Coll_Previous_Same_Season", DbType="VarChar(10)")]
		public string Coll_Previous_Same_Season
		{
			get
			{
				return this._Coll_Previous_Same_Season;
			}
			set
			{
				if ((this._Coll_Previous_Same_Season != value))
				{
					this._Coll_Previous_Same_Season = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Log_upd_time", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Log_upd_time
		{
			get
			{
				return this._Log_upd_time;
			}
			set
			{
				if ((this._Log_upd_time != value))
				{
					this._Log_upd_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Log_upd_user", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Log_upd_user
		{
			get
			{
				return this._Log_upd_user;
			}
			set
			{
				if ((this._Log_upd_user != value))
				{
					this._Log_upd_user = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted_flag", DbType="Int")]
		public System.Nullable<int> Deleted_flag
		{
			get
			{
				return this._Deleted_flag;
			}
			set
			{
				if ((this._Deleted_flag != value))
				{
					this._Deleted_flag = value;
				}
			}
		}
	}
	
	public partial class sp_Interface_GetCountriesResult
	{
		
		private string _Fcst_model;
		
		private string _CountryId;
		
		private string _CountryDesc;
		
		private System.Nullable<int> _Country_Level;
		
		private string _Country_FatherId;
		
		private string _CrossCountryId;
		
		private string _Currency_code;
		
		private System.Nullable<System.DateTime> _Log_upd_time;
		
		private string _Log_upd_user;
		
		private int _Deleted_flag;
		
		public sp_Interface_GetCountriesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_model", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string Fcst_model
		{
			get
			{
				return this._Fcst_model;
			}
			set
			{
				if ((this._Fcst_model != value))
				{
					this._Fcst_model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryId", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CountryId
		{
			get
			{
				return this._CountryId;
			}
			set
			{
				if ((this._CountryId != value))
				{
					this._CountryId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryDesc", DbType="VarChar(50)")]
		public string CountryDesc
		{
			get
			{
				return this._CountryDesc;
			}
			set
			{
				if ((this._CountryDesc != value))
				{
					this._CountryDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country_Level", DbType="Int")]
		public System.Nullable<int> Country_Level
		{
			get
			{
				return this._Country_Level;
			}
			set
			{
				if ((this._Country_Level != value))
				{
					this._Country_Level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country_FatherId", DbType="VarChar(50)")]
		public string Country_FatherId
		{
			get
			{
				return this._Country_FatherId;
			}
			set
			{
				if ((this._Country_FatherId != value))
				{
					this._Country_FatherId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CrossCountryId", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CrossCountryId
		{
			get
			{
				return this._CrossCountryId;
			}
			set
			{
				if ((this._CrossCountryId != value))
				{
					this._CrossCountryId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Currency_code", DbType="VarChar(3)")]
		public string Currency_code
		{
			get
			{
				return this._Currency_code;
			}
			set
			{
				if ((this._Currency_code != value))
				{
					this._Currency_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Log_upd_time", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Log_upd_time
		{
			get
			{
				return this._Log_upd_time;
			}
			set
			{
				if ((this._Log_upd_time != value))
				{
					this._Log_upd_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Log_upd_user", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Log_upd_user
		{
			get
			{
				return this._Log_upd_user;
			}
			set
			{
				if ((this._Log_upd_user != value))
				{
					this._Log_upd_user = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted_flag", DbType="Int NOT NULL")]
		public int Deleted_flag
		{
			get
			{
				return this._Deleted_flag;
			}
			set
			{
				if ((this._Deleted_flag != value))
				{
					this._Deleted_flag = value;
				}
			}
		}
	}
	
	public partial class sp_Interface_GetCustomersResult
	{
		
		private string _Fcst_model;
		
		private string _Fcst_Customer;
		
		private string _Fcst_CustomerD;
		
		private int _Fcst_Cust_Level;
		
		private string _Fcst_Cust_Father;
		
		private int _Fcst_Excluded;
		
		private string _Fcst_Cust_Type;
		
		private System.Nullable<System.DateTime> _log_upd_time;
		
		private string _Log_upd_user;
		
		private int _Deleted_flag;
		
		public sp_Interface_GetCustomersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_model", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string Fcst_model
		{
			get
			{
				return this._Fcst_model;
			}
			set
			{
				if ((this._Fcst_model != value))
				{
					this._Fcst_model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_Customer", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string Fcst_Customer
		{
			get
			{
				return this._Fcst_Customer;
			}
			set
			{
				if ((this._Fcst_Customer != value))
				{
					this._Fcst_Customer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_CustomerD", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string Fcst_CustomerD
		{
			get
			{
				return this._Fcst_CustomerD;
			}
			set
			{
				if ((this._Fcst_CustomerD != value))
				{
					this._Fcst_CustomerD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_Cust_Level", DbType="Int NOT NULL")]
		public int Fcst_Cust_Level
		{
			get
			{
				return this._Fcst_Cust_Level;
			}
			set
			{
				if ((this._Fcst_Cust_Level != value))
				{
					this._Fcst_Cust_Level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_Cust_Father", DbType="VarChar(20)")]
		public string Fcst_Cust_Father
		{
			get
			{
				return this._Fcst_Cust_Father;
			}
			set
			{
				if ((this._Fcst_Cust_Father != value))
				{
					this._Fcst_Cust_Father = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_Excluded", DbType="Int NOT NULL")]
		public int Fcst_Excluded
		{
			get
			{
				return this._Fcst_Excluded;
			}
			set
			{
				if ((this._Fcst_Excluded != value))
				{
					this._Fcst_Excluded = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_Cust_Type", DbType="NVarChar(5)")]
		public string Fcst_Cust_Type
		{
			get
			{
				return this._Fcst_Cust_Type;
			}
			set
			{
				if ((this._Fcst_Cust_Type != value))
				{
					this._Fcst_Cust_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_upd_time", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> log_upd_time
		{
			get
			{
				return this._log_upd_time;
			}
			set
			{
				if ((this._log_upd_time != value))
				{
					this._log_upd_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Log_upd_user", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Log_upd_user
		{
			get
			{
				return this._Log_upd_user;
			}
			set
			{
				if ((this._Log_upd_user != value))
				{
					this._Log_upd_user = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted_flag", DbType="Int NOT NULL")]
		public int Deleted_flag
		{
			get
			{
				return this._Deleted_flag;
			}
			set
			{
				if ((this._Deleted_flag != value))
				{
					this._Deleted_flag = value;
				}
			}
		}
	}
	
	public partial class sp_Interface_GetXCustomersResult
	{
		
		private string _Fcst_model;
		
		private string _Customer_code;
		
		private string _Customer_door;
		
		private string _CrossCustomer_code;
		
		private string _CrossCustomer_door;
		
		private string _CrossCustomer_country;
		
		private System.Nullable<System.DateTime> _log_upd_time;
		
		private string _Log_upd_user;
		
		private int _Deleted_flag;
		
		public sp_Interface_GetXCustomersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_model", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string Fcst_model
		{
			get
			{
				return this._Fcst_model;
			}
			set
			{
				if ((this._Fcst_model != value))
				{
					this._Fcst_model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customer_code", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Customer_code
		{
			get
			{
				return this._Customer_code;
			}
			set
			{
				if ((this._Customer_code != value))
				{
					this._Customer_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customer_door", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Customer_door
		{
			get
			{
				return this._Customer_door;
			}
			set
			{
				if ((this._Customer_door != value))
				{
					this._Customer_door = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CrossCustomer_code", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CrossCustomer_code
		{
			get
			{
				return this._CrossCustomer_code;
			}
			set
			{
				if ((this._CrossCustomer_code != value))
				{
					this._CrossCustomer_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CrossCustomer_door", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CrossCustomer_door
		{
			get
			{
				return this._CrossCustomer_door;
			}
			set
			{
				if ((this._CrossCustomer_door != value))
				{
					this._CrossCustomer_door = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CrossCustomer_country", DbType="VarChar(20)")]
		public string CrossCustomer_country
		{
			get
			{
				return this._CrossCustomer_country;
			}
			set
			{
				if ((this._CrossCustomer_country != value))
				{
					this._CrossCustomer_country = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_upd_time", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> log_upd_time
		{
			get
			{
				return this._log_upd_time;
			}
			set
			{
				if ((this._log_upd_time != value))
				{
					this._log_upd_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Log_upd_user", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Log_upd_user
		{
			get
			{
				return this._Log_upd_user;
			}
			set
			{
				if ((this._Log_upd_user != value))
				{
					this._Log_upd_user = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted_flag", DbType="Int NOT NULL")]
		public int Deleted_flag
		{
			get
			{
				return this._Deleted_flag;
			}
			set
			{
				if ((this._Deleted_flag != value))
				{
					this._Deleted_flag = value;
				}
			}
		}
	}
	
	public partial class sp_Interface_GetXCountriesResult
	{
		
		private string _fcst_model;
		
		private string _countryId;
		
		private string _countryDesc;
		
		public sp_Interface_GetXCountriesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fcst_model", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string fcst_model
		{
			get
			{
				return this._fcst_model;
			}
			set
			{
				if ((this._fcst_model != value))
				{
					this._fcst_model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_countryId", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string countryId
		{
			get
			{
				return this._countryId;
			}
			set
			{
				if ((this._countryId != value))
				{
					this._countryId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_countryDesc", DbType="VarChar(50)")]
		public string countryDesc
		{
			get
			{
				return this._countryDesc;
			}
			set
			{
				if ((this._countryDesc != value))
				{
					this._countryDesc = value;
				}
			}
		}
	}
	
	public partial class sp_Interface_GetImpSeasonsResult
	{
		
		private string _Fcst_model;
		
		private string _Fcst_collection;
		
		private int _Fcst_ImportActive;
		
		private System.Nullable<System.DateTime> _DueDateFrom;
		
		private System.Nullable<System.DateTime> _DueDateTo;
		
		private string _SFA_Collection;
		
		private System.Nullable<System.DateTime> _Storedatefrom;
		
		private System.Nullable<System.DateTime> _Storedateto;
		
		private System.Nullable<System.DateTime> _DeadlineDate;
		
		private System.Nullable<System.DateTime> _ForecastingUntilDate;
		
		private System.Nullable<System.DateTime> _Log_upd_time;
		
		private string _Log_upd_user;
		
		private System.Nullable<int> _Deleted_flag;
		
		public sp_Interface_GetImpSeasonsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_model", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string Fcst_model
		{
			get
			{
				return this._Fcst_model;
			}
			set
			{
				if ((this._Fcst_model != value))
				{
					this._Fcst_model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_collection", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Fcst_collection
		{
			get
			{
				return this._Fcst_collection;
			}
			set
			{
				if ((this._Fcst_collection != value))
				{
					this._Fcst_collection = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_ImportActive", DbType="Int NOT NULL")]
		public int Fcst_ImportActive
		{
			get
			{
				return this._Fcst_ImportActive;
			}
			set
			{
				if ((this._Fcst_ImportActive != value))
				{
					this._Fcst_ImportActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DueDateFrom", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> DueDateFrom
		{
			get
			{
				return this._DueDateFrom;
			}
			set
			{
				if ((this._DueDateFrom != value))
				{
					this._DueDateFrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DueDateTo", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> DueDateTo
		{
			get
			{
				return this._DueDateTo;
			}
			set
			{
				if ((this._DueDateTo != value))
				{
					this._DueDateTo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SFA_Collection", DbType="VarChar(10)")]
		public string SFA_Collection
		{
			get
			{
				return this._SFA_Collection;
			}
			set
			{
				if ((this._SFA_Collection != value))
				{
					this._SFA_Collection = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Storedatefrom", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Storedatefrom
		{
			get
			{
				return this._Storedatefrom;
			}
			set
			{
				if ((this._Storedatefrom != value))
				{
					this._Storedatefrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Storedateto", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Storedateto
		{
			get
			{
				return this._Storedateto;
			}
			set
			{
				if ((this._Storedateto != value))
				{
					this._Storedateto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeadlineDate", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> DeadlineDate
		{
			get
			{
				return this._DeadlineDate;
			}
			set
			{
				if ((this._DeadlineDate != value))
				{
					this._DeadlineDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ForecastingUntilDate", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> ForecastingUntilDate
		{
			get
			{
				return this._ForecastingUntilDate;
			}
			set
			{
				if ((this._ForecastingUntilDate != value))
				{
					this._ForecastingUntilDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Log_upd_time", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Log_upd_time
		{
			get
			{
				return this._Log_upd_time;
			}
			set
			{
				if ((this._Log_upd_time != value))
				{
					this._Log_upd_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Log_upd_user", DbType="VarChar(50)")]
		public string Log_upd_user
		{
			get
			{
				return this._Log_upd_user;
			}
			set
			{
				if ((this._Log_upd_user != value))
				{
					this._Log_upd_user = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted_flag", DbType="Int")]
		public System.Nullable<int> Deleted_flag
		{
			get
			{
				return this._Deleted_flag;
			}
			set
			{
				if ((this._Deleted_flag != value))
				{
					this._Deleted_flag = value;
				}
			}
		}
	}
	
	public partial class sp_Interface_GetEopsSeasonsResult
	{
		
		private string _fcst_model;
		
		private string _Fcst_collection;
		
		private System.Nullable<System.DateTime> _LastDate;
		
		public sp_Interface_GetEopsSeasonsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fcst_model", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string fcst_model
		{
			get
			{
				return this._fcst_model;
			}
			set
			{
				if ((this._fcst_model != value))
				{
					this._fcst_model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_collection", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Fcst_collection
		{
			get
			{
				return this._Fcst_collection;
			}
			set
			{
				if ((this._Fcst_collection != value))
				{
					this._Fcst_collection = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastDate
		{
			get
			{
				return this._LastDate;
			}
			set
			{
				if ((this._LastDate != value))
				{
					this._LastDate = value;
				}
			}
		}
	}
	
	public partial class sp_Interface_GetProdCatResult
	{
		
		private string _Fcst_model;
		
		private string _Prodcat;
		
		public sp_Interface_GetProdCatResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_model", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Fcst_model
		{
			get
			{
				return this._Fcst_model;
			}
			set
			{
				if ((this._Fcst_model != value))
				{
					this._Fcst_model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prodcat", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Prodcat
		{
			get
			{
				return this._Prodcat;
			}
			set
			{
				if ((this._Prodcat != value))
				{
					this._Prodcat = value;
				}
			}
		}
	}
	
	public partial class sp_Interface_GetImportCustomersResult
	{
		
		private string _Fcst_Model;
		
		private int _Fcst_Priority;
		
		private string _Fcst_Customer;
		
		private string _Customer_code;
		
		private string _Delivery_addresscode;
		
		private string _Collection_From;
		
		private string _Collection_To;
		
		private string _Product_Category_From;
		
		private string _Product_Category_To;
		
		private string _Division;
		
		private string _SalesRegion;
		
		private string _CCSalesRegion;
		
		private string _ClassIDFrom;
		
		private string _ClassIDto;
		
		private int _Definition_level;
		
		private string _Comment;
		
		private System.Nullable<System.DateTime> _Log_upd_time;
		
		private string _Log_upd_user;
		
		private int _Deleted_Flag;
		
		public sp_Interface_GetImportCustomersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_Model", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string Fcst_Model
		{
			get
			{
				return this._Fcst_Model;
			}
			set
			{
				if ((this._Fcst_Model != value))
				{
					this._Fcst_Model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_Priority", DbType="Int NOT NULL")]
		public int Fcst_Priority
		{
			get
			{
				return this._Fcst_Priority;
			}
			set
			{
				if ((this._Fcst_Priority != value))
				{
					this._Fcst_Priority = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_Customer", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string Fcst_Customer
		{
			get
			{
				return this._Fcst_Customer;
			}
			set
			{
				if ((this._Fcst_Customer != value))
				{
					this._Fcst_Customer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customer_code", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Customer_code
		{
			get
			{
				return this._Customer_code;
			}
			set
			{
				if ((this._Customer_code != value))
				{
					this._Customer_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Delivery_addresscode", DbType="VarChar(20)")]
		public string Delivery_addresscode
		{
			get
			{
				return this._Delivery_addresscode;
			}
			set
			{
				if ((this._Delivery_addresscode != value))
				{
					this._Delivery_addresscode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Collection_From", DbType="VarChar(5)")]
		public string Collection_From
		{
			get
			{
				return this._Collection_From;
			}
			set
			{
				if ((this._Collection_From != value))
				{
					this._Collection_From = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Collection_To", DbType="VarChar(5)")]
		public string Collection_To
		{
			get
			{
				return this._Collection_To;
			}
			set
			{
				if ((this._Collection_To != value))
				{
					this._Collection_To = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_Category_From", DbType="VarChar(40)")]
		public string Product_Category_From
		{
			get
			{
				return this._Product_Category_From;
			}
			set
			{
				if ((this._Product_Category_From != value))
				{
					this._Product_Category_From = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_Category_To", DbType="VarChar(40)")]
		public string Product_Category_To
		{
			get
			{
				return this._Product_Category_To;
			}
			set
			{
				if ((this._Product_Category_To != value))
				{
					this._Product_Category_To = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Division", DbType="VarChar(20)")]
		public string Division
		{
			get
			{
				return this._Division;
			}
			set
			{
				if ((this._Division != value))
				{
					this._Division = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesRegion", DbType="VarChar(20)")]
		public string SalesRegion
		{
			get
			{
				return this._SalesRegion;
			}
			set
			{
				if ((this._SalesRegion != value))
				{
					this._SalesRegion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCSalesRegion", DbType="VarChar(20)")]
		public string CCSalesRegion
		{
			get
			{
				return this._CCSalesRegion;
			}
			set
			{
				if ((this._CCSalesRegion != value))
				{
					this._CCSalesRegion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassIDFrom", DbType="VarChar(20)")]
		public string ClassIDFrom
		{
			get
			{
				return this._ClassIDFrom;
			}
			set
			{
				if ((this._ClassIDFrom != value))
				{
					this._ClassIDFrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassIDto", DbType="VarChar(20)")]
		public string ClassIDto
		{
			get
			{
				return this._ClassIDto;
			}
			set
			{
				if ((this._ClassIDto != value))
				{
					this._ClassIDto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Definition_level", DbType="Int NOT NULL")]
		public int Definition_level
		{
			get
			{
				return this._Definition_level;
			}
			set
			{
				if ((this._Definition_level != value))
				{
					this._Definition_level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="VarChar(255)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this._Comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Log_upd_time", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Log_upd_time
		{
			get
			{
				return this._Log_upd_time;
			}
			set
			{
				if ((this._Log_upd_time != value))
				{
					this._Log_upd_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Log_upd_user", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Log_upd_user
		{
			get
			{
				return this._Log_upd_user;
			}
			set
			{
				if ((this._Log_upd_user != value))
				{
					this._Log_upd_user = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Deleted Flag]", Storage="_Deleted_Flag", DbType="Int NOT NULL")]
		public int Deleted_Flag
		{
			get
			{
				return this._Deleted_Flag;
			}
			set
			{
				if ((this._Deleted_Flag != value))
				{
					this._Deleted_Flag = value;
				}
			}
		}
	}
	
	public partial class sp_Interface_GetCustomersDoorsResult
	{
		
		private string _Fcst_Model;
		
		private string _Customer_Code;
		
		private string _Customer_Door;
		
		public sp_Interface_GetCustomersDoorsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_Model", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string Fcst_Model
		{
			get
			{
				return this._Fcst_Model;
			}
			set
			{
				if ((this._Fcst_Model != value))
				{
					this._Fcst_Model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customer_Code", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Customer_Code
		{
			get
			{
				return this._Customer_Code;
			}
			set
			{
				if ((this._Customer_Code != value))
				{
					this._Customer_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customer_Door", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Customer_Door
		{
			get
			{
				return this._Customer_Door;
			}
			set
			{
				if ((this._Customer_Door != value))
				{
					this._Customer_Door = value;
				}
			}
		}
	}
	
	public partial class sp_Interface_GetCfgSplitChannelResult
	{
		
		private string _Fcst_model;
		
		private string _SplitChannel;
		
		private string _MainChannel;
		
		private System.Nullable<System.DateTime> _Log_upd_time;
		
		private string _Log_upd_user;
		
		private int _Deleted_flag;
		
		public sp_Interface_GetCfgSplitChannelResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_model", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Fcst_model
		{
			get
			{
				return this._Fcst_model;
			}
			set
			{
				if ((this._Fcst_model != value))
				{
					this._Fcst_model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SplitChannel", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string SplitChannel
		{
			get
			{
				return this._SplitChannel;
			}
			set
			{
				if ((this._SplitChannel != value))
				{
					this._SplitChannel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MainChannel", DbType="VarChar(5)")]
		public string MainChannel
		{
			get
			{
				return this._MainChannel;
			}
			set
			{
				if ((this._MainChannel != value))
				{
					this._MainChannel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Log_upd_time", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Log_upd_time
		{
			get
			{
				return this._Log_upd_time;
			}
			set
			{
				if ((this._Log_upd_time != value))
				{
					this._Log_upd_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Log_upd_user", DbType="VarChar(50)")]
		public string Log_upd_user
		{
			get
			{
				return this._Log_upd_user;
			}
			set
			{
				if ((this._Log_upd_user != value))
				{
					this._Log_upd_user = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted_flag", DbType="Int NOT NULL")]
		public int Deleted_flag
		{
			get
			{
				return this._Deleted_flag;
			}
			set
			{
				if ((this._Deleted_flag != value))
				{
					this._Deleted_flag = value;
				}
			}
		}
	}
	
	public partial class sp_Interface_GetPlantsResult
	{
		
		private string _Fcst_model;
		
		private string _Fcst_Plant;
		
		private int _Priority;
		
		private System.Nullable<System.DateTime> _log_upd_time;
		
		private string _Log_upd_user;
		
		private System.Nullable<int> _Deleted_flag;
		
		private string _Fcst_DC;
		
		public sp_Interface_GetPlantsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_model", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string Fcst_model
		{
			get
			{
				return this._Fcst_model;
			}
			set
			{
				if ((this._Fcst_model != value))
				{
					this._Fcst_model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_Plant", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Fcst_Plant
		{
			get
			{
				return this._Fcst_Plant;
			}
			set
			{
				if ((this._Fcst_Plant != value))
				{
					this._Fcst_Plant = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priority", DbType="Int NOT NULL")]
		public int Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this._Priority = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_upd_time", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> log_upd_time
		{
			get
			{
				return this._log_upd_time;
			}
			set
			{
				if ((this._log_upd_time != value))
				{
					this._log_upd_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Log_upd_user", DbType="VarChar(50)")]
		public string Log_upd_user
		{
			get
			{
				return this._Log_upd_user;
			}
			set
			{
				if ((this._Log_upd_user != value))
				{
					this._Log_upd_user = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted_flag", DbType="Int")]
		public System.Nullable<int> Deleted_flag
		{
			get
			{
				return this._Deleted_flag;
			}
			set
			{
				if ((this._Deleted_flag != value))
				{
					this._Deleted_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_DC", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Fcst_DC
		{
			get
			{
				return this._Fcst_DC;
			}
			set
			{
				if ((this._Fcst_DC != value))
				{
					this._Fcst_DC = value;
				}
			}
		}
	}
	
	public partial class sp_Interface_GetSAPvsTxtResult
	{
		
		private string _Fcst_model;
		
		private string _SAPReqSegment;
		
		private string _SAPPlant;
		
		private System.Nullable<int> _SAPSsnYr;
		
		private string _SAPSsn;
		
		private string _TxtCollection;
		
		private string _TxtChannel;
		
		private string _TxtOrderType;
		
		private string _TxtCustomer;
		
		private System.Nullable<bool> _ExportToSAP;
		
		private string _SAPExtRegId;
		
		private System.Nullable<bool> _FlagAlignSO;
		
		private System.Nullable<bool> _FLagFcst;
		
		private int _DemandOffSetDays;
		
		private System.Nullable<System.DateTime> _Log_Upd_Time;
		
		private string _Log_upd_User;
		
		private System.Nullable<bool> _UsePlant;
		
		private string _Fcst_DC;
		
		public sp_Interface_GetSAPvsTxtResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_model", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Fcst_model
		{
			get
			{
				return this._Fcst_model;
			}
			set
			{
				if ((this._Fcst_model != value))
				{
					this._Fcst_model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAPReqSegment", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string SAPReqSegment
		{
			get
			{
				return this._SAPReqSegment;
			}
			set
			{
				if ((this._SAPReqSegment != value))
				{
					this._SAPReqSegment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAPPlant", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string SAPPlant
		{
			get
			{
				return this._SAPPlant;
			}
			set
			{
				if ((this._SAPPlant != value))
				{
					this._SAPPlant = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAPSsnYr", DbType="Int")]
		public System.Nullable<int> SAPSsnYr
		{
			get
			{
				return this._SAPSsnYr;
			}
			set
			{
				if ((this._SAPSsnYr != value))
				{
					this._SAPSsnYr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAPSsn", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string SAPSsn
		{
			get
			{
				return this._SAPSsn;
			}
			set
			{
				if ((this._SAPSsn != value))
				{
					this._SAPSsn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TxtCollection", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string TxtCollection
		{
			get
			{
				return this._TxtCollection;
			}
			set
			{
				if ((this._TxtCollection != value))
				{
					this._TxtCollection = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TxtChannel", DbType="VarChar(5)")]
		public string TxtChannel
		{
			get
			{
				return this._TxtChannel;
			}
			set
			{
				if ((this._TxtChannel != value))
				{
					this._TxtChannel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TxtOrderType", DbType="VarChar(5)")]
		public string TxtOrderType
		{
			get
			{
				return this._TxtOrderType;
			}
			set
			{
				if ((this._TxtOrderType != value))
				{
					this._TxtOrderType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TxtCustomer", DbType="VarChar(10)")]
		public string TxtCustomer
		{
			get
			{
				return this._TxtCustomer;
			}
			set
			{
				if ((this._TxtCustomer != value))
				{
					this._TxtCustomer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExportToSAP", DbType="Bit")]
		public System.Nullable<bool> ExportToSAP
		{
			get
			{
				return this._ExportToSAP;
			}
			set
			{
				if ((this._ExportToSAP != value))
				{
					this._ExportToSAP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAPExtRegId", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string SAPExtRegId
		{
			get
			{
				return this._SAPExtRegId;
			}
			set
			{
				if ((this._SAPExtRegId != value))
				{
					this._SAPExtRegId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlagAlignSO", DbType="Bit")]
		public System.Nullable<bool> FlagAlignSO
		{
			get
			{
				return this._FlagAlignSO;
			}
			set
			{
				if ((this._FlagAlignSO != value))
				{
					this._FlagAlignSO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLagFcst", DbType="Bit")]
		public System.Nullable<bool> FLagFcst
		{
			get
			{
				return this._FLagFcst;
			}
			set
			{
				if ((this._FLagFcst != value))
				{
					this._FLagFcst = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DemandOffSetDays", DbType="Int NOT NULL")]
		public int DemandOffSetDays
		{
			get
			{
				return this._DemandOffSetDays;
			}
			set
			{
				if ((this._DemandOffSetDays != value))
				{
					this._DemandOffSetDays = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Log_Upd_Time", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Log_Upd_Time
		{
			get
			{
				return this._Log_Upd_Time;
			}
			set
			{
				if ((this._Log_Upd_Time != value))
				{
					this._Log_Upd_Time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Log_upd_User", DbType="VarChar(50)")]
		public string Log_upd_User
		{
			get
			{
				return this._Log_upd_User;
			}
			set
			{
				if ((this._Log_upd_User != value))
				{
					this._Log_upd_User = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsePlant", DbType="Bit")]
		public System.Nullable<bool> UsePlant
		{
			get
			{
				return this._UsePlant;
			}
			set
			{
				if ((this._UsePlant != value))
				{
					this._UsePlant = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_DC", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Fcst_DC
		{
			get
			{
				return this._Fcst_DC;
			}
			set
			{
				if ((this._Fcst_DC != value))
				{
					this._Fcst_DC = value;
				}
			}
		}
	}
	
	public partial class sp_Interface_GetDCsResult
	{
		
		private string _Fcst_model;
		
		private string _Fcst_DC;
		
		private string _Fcst_DC_Description;
		
		private System.Nullable<System.DateTime> _Log_upd_time;
		
		private string _Log_upd_user;
		
		private System.Nullable<int> _Deleted_flag;
		
		public sp_Interface_GetDCsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_model", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string Fcst_model
		{
			get
			{
				return this._Fcst_model;
			}
			set
			{
				if ((this._Fcst_model != value))
				{
					this._Fcst_model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_DC", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Fcst_DC
		{
			get
			{
				return this._Fcst_DC;
			}
			set
			{
				if ((this._Fcst_DC != value))
				{
					this._Fcst_DC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_DC_Description", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Fcst_DC_Description
		{
			get
			{
				return this._Fcst_DC_Description;
			}
			set
			{
				if ((this._Fcst_DC_Description != value))
				{
					this._Fcst_DC_Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Log_upd_time", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Log_upd_time
		{
			get
			{
				return this._Log_upd_time;
			}
			set
			{
				if ((this._Log_upd_time != value))
				{
					this._Log_upd_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Log_upd_user", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Log_upd_user
		{
			get
			{
				return this._Log_upd_user;
			}
			set
			{
				if ((this._Log_upd_user != value))
				{
					this._Log_upd_user = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted_flag", DbType="Int")]
		public System.Nullable<int> Deleted_flag
		{
			get
			{
				return this._Deleted_flag;
			}
			set
			{
				if ((this._Deleted_flag != value))
				{
					this._Deleted_flag = value;
				}
			}
		}
	}
	
	public partial class sp_Interface_GetSizeSplitResult
	{
		
		private string _Fcst_model;
		
		private string _Collection;
		
		private string _Collection_History;
		
		private System.Nullable<System.DateTime> _Log_upd_time;
		
		private string _Log_upd_user;
		
		private int _Deleted_flag;
		
		public sp_Interface_GetSizeSplitResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fcst_model", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string Fcst_model
		{
			get
			{
				return this._Fcst_model;
			}
			set
			{
				if ((this._Fcst_model != value))
				{
					this._Fcst_model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Collection", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Collection
		{
			get
			{
				return this._Collection;
			}
			set
			{
				if ((this._Collection != value))
				{
					this._Collection = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Collection_History", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Collection_History
		{
			get
			{
				return this._Collection_History;
			}
			set
			{
				if ((this._Collection_History != value))
				{
					this._Collection_History = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Log_upd_time", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Log_upd_time
		{
			get
			{
				return this._Log_upd_time;
			}
			set
			{
				if ((this._Log_upd_time != value))
				{
					this._Log_upd_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Log_upd_user", DbType="VarChar(20)")]
		public string Log_upd_user
		{
			get
			{
				return this._Log_upd_user;
			}
			set
			{
				if ((this._Log_upd_user != value))
				{
					this._Log_upd_user = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted_flag", DbType="Int NOT NULL")]
		public int Deleted_flag
		{
			get
			{
				return this._Deleted_flag;
			}
			set
			{
				if ((this._Deleted_flag != value))
				{
					this._Deleted_flag = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
